import type { Provider } from '../providers/types.js';
import type { Tracker, TrackerLabel } from '../trackers/types.js';

export interface SetupDocInput {
  provider: Provider;
  tracker: Tracker;
  owner: string;
  repoSlug: string;
  labels: TrackerLabel[];
  /** True when init created (or verified) the labels itself. */
  labelsHandled: boolean;
  /** Steps init did not perform, to be done by hand. */
  skippedSteps: string[];
}

/** Generates the contents of `.buddy/SETUP.md`. */
export function renderSetupDoc(input: SetupDocInput): string {
  const { provider, tracker, owner, repoSlug, labels, labelsHandled, skippedSteps } = input;
  const lines: string[] = [];

  lines.push(
    '# BuddyCheck setup',
    '',
    `Generated by \`buddycheck init\` for **${repoSlug}** (provider: ${provider.label}, issue tracker: ${tracker.label}).`,
    '',
    'Finish these steps once; after that the loop and the SDD workflows run on their own.',
    '',
    '## 1. Repository secrets',
    '',
    `Add these under **Settings → Secrets and variables → Actions → Repository secrets** of \`${repoSlug}\`:`,
    '',
  );

  for (const secret of provider.setupDoc.secrets) {
    lines.push(`- \`${secret.name}\` — ${secret.description}`);
  }

  lines.push('', '## 2. Repository settings', '');
  for (const setting of provider.setupDoc.repoSettings) {
    lines.push(`- ${setting}`);
  }

  lines.push('', '## 3. Local CLI', '');
  for (const step of provider.setupDoc.cliInstall) {
    lines.push(`- ${step}`);
  }

  lines.push(
    '',
    '## 4. How to trigger it',
    '',
    '**SDD workflows** — comment on an issue (or its comments); only comments authored by',
    `\`${owner}\` are honoured, everything else is ignored:`,
    '',
    '| Comment     | What it does                                                        |',
    '| ----------- | ------------------------------------------------------------------- |',
    '| `!grill`    | Grills the idea in the issue and shapes it into a spec.             |',
    '| `!to-plan`  | Turns the grilled spec into a plan plus suggested issue slices.     |',
    '| `!to-issues`| Creates the slice issues from the plan.                             |',
    '',
    '**Agent loop**',
    '',
    '- On GitHub: Actions → **Buddy - Once** → *Run workflow* (`workflow_dispatch`).',
    '- Locally: `bash .buddy/buddy-once.sh` — picks an issue labelled `ready-for-agent`,',
    '  runs the coder agent, then the oracle review, and opens a pull request.',
    '',
    '## 5. Labels',
    '',
  );

  if (labelsHandled) {
    lines.push(`These labels exist in \`${repoSlug}\` (created or verified during init):`, '');
  } else {
    lines.push(
      `Label creation was **not** performed. Create these in \`${repoSlug}\` before using the workflows`,
      '(`gh label create <name> --color <color> --description "<description>"`):',
      '',
    );
  }

  lines.push('| Label | Color | Meaning |', '| ----- | ----- | ------- |');
  for (const label of labels) {
    lines.push(`| \`${label.name}\` | \`#${label.color}\` | ${label.description} |`);
  }

  lines.push('', '## 6. Steps left for you', '');
  if (skippedSteps.length === 0) {
    lines.push('Nothing — init completed every automated step.');
  } else {
    for (const step of skippedSteps) {
      lines.push(`- [ ] ${step}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}
