#!/usr/bin/env bash
# test-to-issues-workflow.sh
#
# Structural verification for issue #11: the `!to-issues` SDD command must
# trigger on an issue_comment authored by exactly `KilianJimenez` whose body
# starts with `!to-issues`, run a dedicated `spec-to-issues` agent that reads
# the approved plan + suggested issues from the conversation, creates the
# corresponding vertical-slice issues (each linked back to the source issue
# and labeled `ready-for-agent`), posts a single summary comment on the
# source issue, and lands the source issue on the `sdd:issues-created` label.
#
# This repo has no application runtime to unit test against — the "seams"
# under test here are the two authored artifacts (the workflow trigger/
# permissions and the spec-to-issues agent doc) that must contain specific,
# load-bearing content. Run this script directly:
# `bash .github/tests/test-to-issues-workflow.sh`.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORKFLOW="$ROOT/.github/workflows/to-issues.yml"
AGENT="$ROOT/.github/agents/spec-to-issues.agent.md"

fail=0

check() {
  local desc="$1"
  local result="$2"
  if [ "$result" -eq 0 ]; then
    echo "PASS: $desc"
  else
    echo "FAIL: $desc"
    fail=1
  fi
}

# --- to-issues.yml checks ---
[ -f "$WORKFLOW" ]
check "to-issues.yml exists" $?

if [ -f "$WORKFLOW" ]; then
  grep -q "issue_comment:" "$WORKFLOW"
  check "workflow triggers on issue_comment" $?

  grep -q "types: \[created\]" "$WORKFLOW"
  check "workflow triggers on comment creation" $?

  grep -q "github.event.comment.user.login == 'KilianJimenez'" "$WORKFLOW"
  check "workflow gates on exact login KilianJimenez" $?

  grep -q "startsWith(github.event.comment.body, '!to-issues')" "$WORKFLOW"
  check "workflow gates on startsWith('!to-issues')" $?

  grep -q "issues: write" "$WORKFLOW"
  check "workflow requests issues: write permission" $?

  grep -q "contents: read" "$WORKFLOW"
  check "workflow requests contents: read permission" $?

  grep -q "COPILOT_CLI_TOKEN" "$WORKFLOW"
  check "workflow uses COPILOT_CLI_TOKEN secret" $?

  grep -q -- "--agent=spec-to-issues" "$WORKFLOW"
  check "workflow invokes the spec-to-issues agent" $?

  python3 -c "import yaml,sys; yaml.safe_load(open('$WORKFLOW'))" >/dev/null 2>&1
  check "workflow is valid YAML" $?
fi

# --- spec-to-issues.agent.md checks ---
[ -f "$AGENT" ]
check "spec-to-issues.agent.md exists" $?

if [ -f "$AGENT" ]; then
  grep -q "^name: spec-to-issues" "$AGENT"
  check "agent frontmatter declares name: spec-to-issues" $?

  grep -q "to-issues" "$AGENT"
  check "agent doc references the to-issues skill" $?

  grep -qi "vertical.slice\|tracer.bullet" "$AGENT"
  check "agent doc embeds vertical-slice/tracer-bullet conventions" $?

  grep -q "Part of #" "$AGENT"
  check "agent doc links created issues back with 'Part of #'" $?

  grep -q "ready-for-agent" "$AGENT"
  check "agent doc labels created issues ready-for-agent" $?

  grep -q "summary comment\|summary of the created issues" "$AGENT"
  check "agent doc posts a summary comment on the source issue" $?

  grep -q "This was generated by AI" "$AGENT"
  check "agent doc includes the AI disclaimer line" $?

  grep -q "sdd:issues-created" "$AGENT"
  check "agent doc sets the sdd:issues-created label" $?

  grep -q -- "--remove-label \"sdd:grilling\"" "$AGENT" && grep -q -- "--remove-label \"sdd:planned\"" "$AGENT"
  check "agent doc removes conflicting sdd: state labels" $?

  grep -qi "do not close\|does not close" "$AGENT"
  check "agent doc forbids closing the parent issue" $?
fi

if [ "$fail" -eq 0 ]; then
  echo "All checks passed."
else
  echo "Some checks failed."
fi

exit $fail
