#!/usr/bin/env bash
# test-to-plan-workflow.sh
#
# Structural verification for issue #10: the `!to-plan` SDD command must
# trigger on an issue_comment authored by exactly `KilianJimenez` whose body
# starts with `!to-plan`, run a dedicated `spec-planner` agent that posts a
# single plan+suggested-issues comment (prefixed with the AI disclaimer) and
# creates no issues, and land the issue on the `sdd:planned` label.
#
# This repo has no application runtime to unit test against — the "seams"
# under test here are the two authored artifacts (the workflow trigger/
# permissions and the spec-planner agent doc) that must contain specific,
# load-bearing content. Run this script directly:
# `bash .github/tests/test-to-plan-workflow.sh`.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORKFLOW="$ROOT/.github/workflows/create-plan-and-issues.yml"
AGENT="$ROOT/.github/agents/spec-planner.agent.md"

fail=0

check() {
  local desc="$1"
  local result="$2"
  if [ "$result" -eq 0 ]; then
    echo "PASS: $desc"
  else
    echo "FAIL: $desc"
    fail=1
  fi
}

# --- create-plan-and-issues.yml checks ---
[ -f "$WORKFLOW" ]
check "create-plan-and-issues.yml exists" $?

if [ -f "$WORKFLOW" ]; then
  grep -q "issue_comment:" "$WORKFLOW"
  check "workflow triggers on issue_comment" $?

  grep -q "types: \[created\]" "$WORKFLOW"
  check "workflow triggers on comment creation" $?

  grep -q "github.event.comment.user.login == 'KilianJimenez'" "$WORKFLOW"
  check "workflow gates on exact login KilianJimenez" $?

  grep -q "startsWith(github.event.comment.body, '!to-plan')" "$WORKFLOW"
  check "workflow gates on startsWith('!to-plan')" $?

  grep -q "issues: write" "$WORKFLOW"
  check "workflow requests issues: write permission" $?

  grep -q "contents: read" "$WORKFLOW"
  check "workflow requests contents: read permission" $?

  grep -q "COPILOT_CLI_TOKEN" "$WORKFLOW"
  check "workflow uses COPILOT_CLI_TOKEN secret" $?

  grep -q -- "--agent=spec-planner" "$WORKFLOW"
  check "workflow invokes the spec-planner agent" $?

  python3 -c "import yaml,sys; yaml.safe_load(open('$WORKFLOW'))" >/dev/null 2>&1
  check "workflow is valid YAML" $?
fi

# --- spec-planner.agent.md checks ---
[ -f "$AGENT" ]
check "spec-planner.agent.md exists" $?

if [ -f "$AGENT" ]; then
  grep -q "^name: spec-planner" "$AGENT"
  check "agent frontmatter declares name: spec-planner" $?

  grep -qi "plan" "$AGENT" && grep -qi "suggested" "$AGENT"
  check "agent doc describes planning + suggested issues" $?

  grep -q "single new comment\|single comment" "$AGENT"
  check "agent doc requires posting plan + suggestions in one comment" $?

  grep -qi "Do NOT create any issues" "$AGENT"
  check "agent doc forbids creating issues in this step" $?

  grep -q "This was generated by AI during planning" "$AGENT"
  check "agent doc includes the AI disclaimer line" $?

  grep -q "sdd:planned" "$AGENT"
  check "agent doc sets the sdd:planned label" $?

  grep -q -- "--remove-label \"sdd:grilling\"" "$AGENT" && grep -q -- "--remove-label \"sdd:issues-created\"" "$AGENT"
  check "agent doc removes conflicting sdd: state labels" $?
fi

if [ "$fail" -eq 0 ]; then
  echo "All checks passed."
else
  echo "Some checks failed."
fi

exit $fail
