#!/usr/bin/env bash
# test-grill-workflow.sh
#
# BuddyCheck structural verification: the `!grill` SDD command must trigger on
# an issue_comment authored by exactly the configured owner login whose body
# starts with `!grill`, run a dedicated `grill-my-idea` agent that posts one
# round of clarifying questions as a single comment (prefixed with the AI
# disclaimer), and land the issue on the `sdd:grilling` label.
#
# These checks target authored artifacts rather than application runtime —
# the "seams" under test are the generated workflow (trigger/permissions) and
# the grill-my-idea agent doc, which must contain specific, load-bearing
# content.
#
# Usage: bash tests/structural/test-grill-workflow.sh [TARGET_ROOT]
#   TARGET_ROOT defaults to `.` — the root of a repo scaffolded by
#   `npx buddycheck init`.
#   Set EXPECTED_OWNER to additionally assert the exact gated login.

set -uo pipefail

ROOT="$(cd "${1:-.}" && pwd)"
WORKFLOW="$ROOT/.github/workflows/grill.yml"
AGENT="$ROOT/.github/agents/grill-my-idea.agent.md"

fail=0

check() {
  local desc="$1"
  local result="$2"
  if [ "$result" -eq 0 ]; then
    echo "PASS: $desc"
  else
    echo "FAIL: $desc"
    fail=1
  fi
}

# --- grill.yml checks ---
[ -f "$WORKFLOW" ]
check "grill.yml exists" $?

if [ -f "$WORKFLOW" ]; then
  grep -q "issue_comment:" "$WORKFLOW"
  check "workflow triggers on issue_comment" $?

  grep -q "types: \[created\]" "$WORKFLOW"
  check "workflow triggers on comment creation" $?

  grep -q "github.event.comment.user.login == '[^']\+'" "$WORKFLOW"
  check "workflow gates on an exact comment author login" $?

  if [ -n "${EXPECTED_OWNER:-}" ]; then
    grep -q "github.event.comment.user.login == '${EXPECTED_OWNER}'" "$WORKFLOW"
    check "workflow gates on the expected owner login ($EXPECTED_OWNER)" $?
  fi

  grep -q "startsWith(github.event.comment.body, '!grill')" "$WORKFLOW"
  check "workflow gates on startsWith('!grill')" $?

  grep -q "issues: write" "$WORKFLOW"
  check "workflow requests issues: write permission" $?

  grep -q "contents: read" "$WORKFLOW"
  check "workflow requests contents: read permission" $?

  grep -q "COPILOT_CLI_TOKEN" "$WORKFLOW"
  check "workflow uses COPILOT_CLI_TOKEN secret" $?

  grep -q -- "--agent=grill-my-idea" "$WORKFLOW"
  check "workflow invokes the grill-my-idea agent" $?

  if python3 -c "import yaml" >/dev/null 2>&1; then
    python3 -c "import yaml,sys; yaml.safe_load(open(sys.argv[1]))" "$WORKFLOW" >/dev/null 2>&1
    check "workflow is valid YAML" $?
  else
    echo "SKIP: workflow YAML validation (python3 + PyYAML unavailable)"
  fi
fi

# --- grill-my-idea.agent.md checks ---
[ -f "$AGENT" ]
check "grill-my-idea.agent.md exists" $?

if [ -f "$AGENT" ]; then
  grep -q "^name: grill-my-idea" "$AGENT"
  check "agent frontmatter declares name: grill-my-idea" $?

  grep -qi "clarifying question" "$AGENT"
  check "agent doc describes posting clarifying questions" $?

  grep -qi "one round" "$AGENT"
  check "agent doc limits output to one round per invocation" $?

  grep -qi "do not propose a plan\|do not write a plan\|you do not write a plan" "$AGENT"
  check "agent doc forbids proposing a plan or implementation" $?

  grep -q "This was generated by AI" "$AGENT"
  check "agent doc includes the AI disclaimer line" $?

  grep -q "sdd:grilling" "$AGENT"
  check "agent doc sets the sdd:grilling label" $?

  grep -q -- "--remove-label \"sdd:planned\"" "$AGENT" && grep -q -- "--remove-label \"sdd:issues-created\"" "$AGENT"
  check "agent doc removes conflicting sdd: state labels" $?

  grep -qi "do not modify any source code\|do not modify.*source code" "$AGENT"
  check "agent Rules disallow source code edits" $?
fi

if [ "$fail" -eq 0 ]; then
  echo "All checks passed."
else
  echo "Some checks failed."
fi

exit $fail
