#!/usr/bin/env bash
# test-to-issues-workflow.sh
#
# BuddyCheck structural verification: the `!to-issues` SDD command must
# trigger on an issue_comment authored by exactly the configured owner login
# whose body starts with `!to-issues`, run a dedicated `spec-to-issues` agent
# that reads the approved plan + suggested issues from the conversation,
# creates the corresponding vertical-slice issues (each linked back to the
# source issue and labeled `ready-for-agent`), posts a single summary comment
# on the source issue, and lands the source issue on the
# `sdd:issues-created` label.
#
# These checks target authored artifacts rather than application runtime —
# the "seams" under test are the generated workflow (trigger/permissions) and
# the spec-to-issues agent doc, which must contain specific, load-bearing
# content.
#
# Usage: bash tests/structural/test-to-issues-workflow.sh [TARGET_ROOT]
#   TARGET_ROOT defaults to `.` — the root of a repo scaffolded by
#   `npx buddycheck init`.
#   Set EXPECTED_OWNER to additionally assert the exact gated login.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tests/structural/lib.sh
source "$HERE/lib.sh"

ROOT="$(cd "${1:-.}" && pwd)"
init_provider_conventions "$ROOT"
WORKFLOW="$ROOT/.github/workflows/to-issues.yml"
AGENT="$AGENT_DIR/spec-to-issues$AGENT_EXT"

fail=0

check() {
  local desc="$1"
  local result="$2"
  if [ "$result" -eq 0 ]; then
    echo "PASS: $desc"
  else
    echo "FAIL: $desc"
    fail=1
  fi
}

# --- to-issues.yml checks ---
[ -f "$WORKFLOW" ]
check "to-issues.yml exists" $?

if [ -f "$WORKFLOW" ]; then
  grep -q "issue_comment:" "$WORKFLOW"
  check "workflow triggers on issue_comment" $?

  grep -q "types: \[created\]" "$WORKFLOW"
  check "workflow triggers on comment creation" $?

  grep -q "github.event.comment.user.login == '[^']\+'" "$WORKFLOW"
  check "workflow gates on an exact comment author login" $?

  if [ -n "${EXPECTED_OWNER:-}" ]; then
    grep -q "github.event.comment.user.login == '${EXPECTED_OWNER}'" "$WORKFLOW"
    check "workflow gates on the expected owner login ($EXPECTED_OWNER)" $?
  fi

  grep -q "startsWith(github.event.comment.body, '!to-issues')" "$WORKFLOW"
  check "workflow gates on startsWith('!to-issues')" $?

  grep -q "issues: write" "$WORKFLOW"
  check "workflow requests issues: write permission" $?

  grep -q "contents: read" "$WORKFLOW"
  check "workflow requests contents: read permission" $?

  grep -q "$CLI_TOKEN_SECRET" "$WORKFLOW"
  check "workflow uses $CLI_TOKEN_SECRET secret" $?

  check_agent_invocation "$WORKFLOW" "spec-to-issues"
  check "workflow invokes the spec-to-issues agent" $?

  if python3 -c "import yaml" >/dev/null 2>&1; then
    python3 -c "import yaml,sys; yaml.safe_load(open(sys.argv[1]))" "$WORKFLOW" >/dev/null 2>&1
    check "workflow is valid YAML" $?
  else
    echo "SKIP: workflow YAML validation (python3 + PyYAML unavailable)"
  fi
fi

# --- spec-to-issues.agent.md checks ---
[ -f "$AGENT" ]
check "spec-to-issues.agent.md exists" $?

if [ -f "$AGENT" ]; then
  check_agent_frontmatter_name "$AGENT" "spec-to-issues"
  check "agent frontmatter declares name: spec-to-issues" $?

  grep -q "to-issues" "$AGENT" || basename "$AGENT" | grep -q "to-issues"
  check "agent doc references the to-issues command" $?

  grep -qi "vertical.slice\|tracer.bullet" "$AGENT"
  check "agent doc embeds vertical-slice/tracer-bullet conventions" $?

  grep -q "Part of #" "$AGENT"
  check "agent doc links created issues back with 'Part of #'" $?

  grep -q "ready-for-agent" "$AGENT"
  check "agent doc labels created issues ready-for-agent" $?

  grep -q "summary comment\|summary of the created issues" "$AGENT"
  check "agent doc posts a summary comment on the source issue" $?

  grep -q "This was generated by AI" "$AGENT"
  check "agent doc includes the AI disclaimer line" $?

  grep -q "sdd:issues-created" "$AGENT"
  check "agent doc sets the sdd:issues-created label" $?

  grep -q -- "--remove-label \"sdd:grilling\"" "$AGENT" && grep -q -- "--remove-label \"sdd:planned\"" "$AGENT"
  check "agent doc removes conflicting sdd: state labels" $?

  grep -qi "do not close\|does not close" "$AGENT"
  check "agent doc forbids closing the parent issue" $?
fi

if [ "$fail" -eq 0 ]; then
  echo "All checks passed."
else
  echo "Some checks failed."
fi

exit $fail
