#!/usr/bin/env bash
# test-to-plan-workflow.sh
#
# BuddyCheck structural verification: the `!to-plan` SDD command must trigger
# on an issue_comment authored by exactly the configured owner login whose
# body starts with `!to-plan`, run a dedicated `spec-planner` agent that posts
# a single plan+suggested-issues comment (prefixed with the AI disclaimer) and
# creates no issues, and land the issue on the `sdd:planned` label.
#
# These checks target authored artifacts rather than application runtime —
# the "seams" under test are the generated workflow (trigger/permissions) and
# the spec-planner agent doc, which must contain specific, load-bearing
# content.
#
# Usage: bash tests/structural/test-to-plan-workflow.sh [TARGET_ROOT]
#   TARGET_ROOT defaults to `.` — the root of a repo scaffolded by
#   `npx buddycheck init`.
#   Set EXPECTED_OWNER to additionally assert the exact gated login.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tests/structural/lib.sh
source "$HERE/lib.sh"

ROOT="$(cd "${1:-.}" && pwd)"
init_provider_conventions "$ROOT"
WORKFLOW="$ROOT/.github/workflows/to-plan.yml"
AGENT="$AGENT_DIR/spec-planner$AGENT_EXT"

fail=0

check() {
  local desc="$1"
  local result="$2"
  if [ "$result" -eq 0 ]; then
    echo "PASS: $desc"
  else
    echo "FAIL: $desc"
    fail=1
  fi
}

# --- to-plan.yml checks ---
[ -f "$WORKFLOW" ]
check "to-plan.yml exists" $?

if [ -f "$WORKFLOW" ]; then
  grep -q "issue_comment:" "$WORKFLOW"
  check "workflow triggers on issue_comment" $?

  grep -q "types: \[created\]" "$WORKFLOW"
  check "workflow triggers on comment creation" $?

  grep -q "github.event.comment.user.login == '[^']\+'" "$WORKFLOW"
  check "workflow gates on an exact comment author login" $?

  if [ -n "${EXPECTED_OWNER:-}" ]; then
    grep -q "github.event.comment.user.login == '${EXPECTED_OWNER}'" "$WORKFLOW"
    check "workflow gates on the expected owner login ($EXPECTED_OWNER)" $?
  fi

  grep -q "startsWith(github.event.comment.body, '!to-plan')" "$WORKFLOW"
  check "workflow gates on startsWith('!to-plan')" $?

  grep -q "issues: write" "$WORKFLOW"
  check "workflow requests issues: write permission" $?

  grep -q "contents: read" "$WORKFLOW"
  check "workflow requests contents: read permission" $?

  grep -q "$CLI_TOKEN_SECRET" "$WORKFLOW"
  check "workflow uses $CLI_TOKEN_SECRET secret" $?

  check_agent_invocation "$WORKFLOW" "spec-planner"
  check "workflow invokes the spec-planner agent" $?

  if python3 -c "import yaml" >/dev/null 2>&1; then
    python3 -c "import yaml,sys; yaml.safe_load(open(sys.argv[1]))" "$WORKFLOW" >/dev/null 2>&1
    check "workflow is valid YAML" $?
  else
    echo "SKIP: workflow YAML validation (python3 + PyYAML unavailable)"
  fi
fi

# --- spec-planner.agent.md checks ---
[ -f "$AGENT" ]
check "spec-planner.agent.md exists" $?

if [ -f "$AGENT" ]; then
  check_agent_frontmatter_name "$AGENT" "spec-planner"
  check "agent frontmatter declares name: spec-planner" $?

  grep -qi "plan" "$AGENT" && grep -qi "suggested" "$AGENT"
  check "agent doc describes planning + suggested issues" $?

  grep -q "single new comment\|single comment" "$AGENT"
  check "agent doc requires posting plan + suggestions in one comment" $?

  grep -qi "Do NOT create any issues" "$AGENT"
  check "agent doc forbids creating issues in this step" $?

  grep -q "This was generated by AI during planning" "$AGENT"
  check "agent doc includes the AI disclaimer line" $?

  grep -q "sdd:planned" "$AGENT"
  check "agent doc sets the sdd:planned label" $?

  grep -q -- "--remove-label \"sdd:grilling\"" "$AGENT" && grep -q -- "--remove-label \"sdd:issues-created\"" "$AGENT"
  check "agent doc removes conflicting sdd: state labels" $?
fi

if [ "$fail" -eq 0 ]; then
  echo "All checks passed."
else
  echo "Some checks failed."
fi

exit $fail
